// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsG89XzB8gSWMy5YAYS4vWKAZGt9LmkL8',
    appId: '1:1063900529601:web:d3f423f20766139ed9e540',
    messagingSenderId: '1063900529601',
    projectId: 'tcinhide',
    authDomain: 'tcinhide.firebaseapp.com',
    databaseURL: 'https://tcinhide-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tcinhide.appspot.com',
    measurementId: 'G-2XL8SF77ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_yPy2N5zV-_EY59UDdlLG6Gc4dzCz18Q',
    appId: '1:1063900529601:android:3f3f58ae294b1e7ed9e540',
    messagingSenderId: '1063900529601',
    projectId: 'tcinhide',
    databaseURL: 'https://tcinhide-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tcinhide.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlLYr8fviNnHd4a15TCN1atV_8kzQ7a7U',
    appId: '1:1063900529601:ios:078b065da46dca82d9e540',
    messagingSenderId: '1063900529601',
    projectId: 'tcinhide',
    databaseURL: 'https://tcinhide-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tcinhide.appspot.com',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlLYr8fviNnHd4a15TCN1atV_8kzQ7a7U',
    appId: '1:1063900529601:ios:078b065da46dca82d9e540',
    messagingSenderId: '1063900529601',
    projectId: 'tcinhide',
    databaseURL: 'https://tcinhide-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tcinhide.appspot.com',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsG89XzB8gSWMy5YAYS4vWKAZGt9LmkL8',
    appId: '1:1063900529601:web:44f125f98eeda21dd9e540',
    messagingSenderId: '1063900529601',
    projectId: 'tcinhide',
    authDomain: 'tcinhide.firebaseapp.com',
    databaseURL: 'https://tcinhide-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tcinhide.appspot.com',
    measurementId: 'G-NCQHSDQNRJ',
  );

}